version: "3"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.database
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: joreju
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default

  web:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - database
    networks:
      - default

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.adminphp
    links:
      - database
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: joreju
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
